!SESSION 2016-08-16 10:38:06.448 -----------------------------------------------
eclipse.buildId=4.6.0.I20160606-1100
java.version=1.8.0_51
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_IN
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -data C:\Users\nikhil_mohandas\eclipse\neon\Python -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.egit.ui 2 0 2016-08-16 10:38:20.986
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\nikhil_mohandas'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2016-08-16 10:39:07.757
!MESSAGE - Ok, file is non-null. Getting info on:C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe -u C:\Users\nikhil_mohandas\.p2\pool\plugins\org.python.pydev_5.1.2.201606231256\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe -u C:\Users\nikhil_mohandas\.p2\pool\plugins\org.python.pydev_5.1.2.201606231256\pysrc\interpreterInfo.py
- Setting task name:Making exec... C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe -u C:\Users\nikhil_mohandas\.p2\pool\plugins\org.python.pydev_5.1.2.201606231256\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Success getting the info. Result:<xml>
<name>python</name>
<version>3.5</version>
<executable>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe</executable>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools-24.0.2-py3.5.egg</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\email-6.0.0a1-py3.5.egg</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\DLLs</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\win32</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\win32\lib</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\Pythonwin</lib>
<forced_lib>Image</forced_lib>
<forced_lib>OpenGL</forced_lib>
<forced_lib>_ast</forced_lib>
<forced_lib>_bisect</forced_lib>
<forced_lib>_bytesio</forced_lib>
<forced_lib>_codecs</forced_lib>
<forced_lib>_codecs_cn</forced_lib>
<forced_lib>_codecs_hk</forced_lib>
<forced_lib>_codecs_iso2022</forced_lib>
<forced_lib>_codecs_jp</forced_lib>
<forced_lib>_codecs_kr</forced_lib>
<forced_lib>_codecs_tw</forced_lib>
<forced_lib>_collections</forced_lib>
<forced_lib>_csv</forced_lib>
<forced_lib>_datetime</forced_lib>
<forced_lib>_fileio</forced_lib>
<forced_lib>_functools</forced_lib>
<forced_lib>_heapq</forced_lib>
<forced_lib>_hotshot</forced_lib>
<forced_lib>_imp</forced_lib>
<forced_lib>_io</forced_lib>
<forced_lib>_json</forced_lib>
<forced_lib>_locale</forced_lib>
<forced_lib>_lsprof</forced_lib>
<forced_lib>_md5</forced_lib>
<forced_lib>_multibytecodec</forced_lib>
<forced_lib>_opcode</forced_lib>
<forced_lib>_operator</forced_lib>
<forced_lib>_pickle</forced_lib>
<forced_lib>_random</forced_lib>
<forced_lib>_sha</forced_lib>
<forced_lib>_sha1</forced_lib>
<forced_lib>_sha256</forced_lib>
<forced_lib>_sha512</forced_lib>
<forced_lib>_signal</forced_lib>
<forced_lib>_sre</forced_lib>
<forced_lib>_stat</forced_lib>
<forced_lib>_string</forced_lib>
<forced_lib>_struct</forced_lib>
<forced_lib>_subprocess</forced_lib>
<forced_lib>_symtable</forced_lib>
<forced_lib>_thread</forced_lib>
<forced_lib>_tracemalloc</forced_lib>
<forced_lib>_warnings</forced_lib>
<forced_lib>_weakref</forced_lib>
<forced_lib>_winapi</forced_lib>
<forced_lib>_winreg</forced_lib>
<forced_lib>array</forced_lib>
<forced_lib>atexit</forced_lib>
<forced_lib>audioop</forced_lib>
<forced_lib>binascii</forced_lib>
<forced_lib>builtins</forced_lib>
<forced_lib>cPickle</forced_lib>
<forced_lib>cStringIO</forced_lib>
<forced_lib>cmath</forced_lib>
<forced_lib>datetime</forced_lib>
<forced_lib>email</forced_lib>
<forced_lib>errno</forced_lib>
<forced_lib>exceptions</forced_lib>
<forced_lib>faulthandler</forced_lib>
<forced_lib>future_builtins</forced_lib>
<forced_lib>gc</forced_lib>
<forced_lib>gi</forced_lib>
<forced_lib>hashlib</forced_lib>
<forced_lib>imageop</forced_lib>
<forced_lib>imp</forced_lib>
<forced_lib>itertools</forced_lib>
<forced_lib>marshal</forced_lib>
<forced_lib>math</forced_lib>
<forced_lib>mmap</forced_lib>
<forced_lib>mock</forced_lib>
<forced_lib>msvcrt</forced_lib>
<forced_lib>multiprocessing</forced_lib>
<forced_lib>nt</forced_lib>
<forced_lib>numpy</forced_lib>
<forced_lib>operator</forced_lib>
<forced_lib>os</forced_lib>
<forced_lib>os.path</forced_lib>
<forced_lib>parser</forced_lib>
<forced_lib>pytest</forced_lib>
<forced_lib>scipy</forced_lib>
<forced_lib>signal</forced_lib>
<forced_lib>socket</forced_lib>
<forced_lib>strop</forced_lib>
<forced_lib>sys</forced_lib>
<forced_lib>thread</forced_lib>
<forced_lib>time</forced_lib>
<forced_lib>winreg</forced_lib>
<forced_lib>wx</forced_lib>
<forced_lib>wxPython</forced_lib>
<forced_lib>xxsubtype</forced_lib>
<forced_lib>zipimport</forced_lib>
<forced_lib>zlib</forced_lib>
</xml>

!STACK 0
java.lang.RuntimeException: - Ok, file is non-null. Getting info on:C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe -u C:\Users\nikhil_mohandas\.p2\pool\plugins\org.python.pydev_5.1.2.201606231256\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe -u C:\Users\nikhil_mohandas\.p2\pool\plugins\org.python.pydev_5.1.2.201606231256\pysrc\interpreterInfo.py
- Setting task name:Making exec... C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe -u C:\Users\nikhil_mohandas\.p2\pool\plugins\org.python.pydev_5.1.2.201606231256\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Success getting the info. Result:<xml>
<name>python</name>
<version>3.5</version>
<executable>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe</executable>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools-24.0.2-py3.5.egg</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\email-6.0.0a1-py3.5.egg</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\DLLs</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\win32</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\win32\lib</lib>
<lib>C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\Pythonwin</lib>
<forced_lib>Image</forced_lib>
<forced_lib>OpenGL</forced_lib>
<forced_lib>_ast</forced_lib>
<forced_lib>_bisect</forced_lib>
<forced_lib>_bytesio</forced_lib>
<forced_lib>_codecs</forced_lib>
<forced_lib>_codecs_cn</forced_lib>
<forced_lib>_codecs_hk</forced_lib>
<forced_lib>_codecs_iso2022</forced_lib>
<forced_lib>_codecs_jp</forced_lib>
<forced_lib>_codecs_kr</forced_lib>
<forced_lib>_codecs_tw</forced_lib>
<forced_lib>_collections</forced_lib>
<forced_lib>_csv</forced_lib>
<forced_lib>_datetime</forced_lib>
<forced_lib>_fileio</forced_lib>
<forced_lib>_functools</forced_lib>
<forced_lib>_heapq</forced_lib>
<forced_lib>_hotshot</forced_lib>
<forced_lib>_imp</forced_lib>
<forced_lib>_io</forced_lib>
<forced_lib>_json</forced_lib>
<forced_lib>_locale</forced_lib>
<forced_lib>_lsprof</forced_lib>
<forced_lib>_md5</forced_lib>
<forced_lib>_multibytecodec</forced_lib>
<forced_lib>_opcode</forced_lib>
<forced_lib>_operator</forced_lib>
<forced_lib>_pickle</forced_lib>
<forced_lib>_random</forced_lib>
<forced_lib>_sha</forced_lib>
<forced_lib>_sha1</forced_lib>
<forced_lib>_sha256</forced_lib>
<forced_lib>_sha512</forced_lib>
<forced_lib>_signal</forced_lib>
<forced_lib>_sre</forced_lib>
<forced_lib>_stat</forced_lib>
<forced_lib>_string</forced_lib>
<forced_lib>_struct</forced_lib>
<forced_lib>_subprocess</forced_lib>
<forced_lib>_symtable</forced_lib>
<forced_lib>_thread</forced_lib>
<forced_lib>_tracemalloc</forced_lib>
<forced_lib>_warnings</forced_lib>
<forced_lib>_weakref</forced_lib>
<forced_lib>_winapi</forced_lib>
<forced_lib>_winreg</forced_lib>
<forced_lib>array</forced_lib>
<forced_lib>atexit</forced_lib>
<forced_lib>audioop</forced_lib>
<forced_lib>binascii</forced_lib>
<forced_lib>builtins</forced_lib>
<forced_lib>cPickle</forced_lib>
<forced_lib>cStringIO</forced_lib>
<forced_lib>cmath</forced_lib>
<forced_lib>datetime</forced_lib>
<forced_lib>email</forced_lib>
<forced_lib>errno</forced_lib>
<forced_lib>exceptions</forced_lib>
<forced_lib>faulthandler</forced_lib>
<forced_lib>future_builtins</forced_lib>
<forced_lib>gc</forced_lib>
<forced_lib>gi</forced_lib>
<forced_lib>hashlib</forced_lib>
<forced_lib>imageop</forced_lib>
<forced_lib>imp</forced_lib>
<forced_lib>itertools</forced_lib>
<forced_lib>marshal</forced_lib>
<forced_lib>math</forced_lib>
<forced_lib>mmap</forced_lib>
<forced_lib>mock</forced_lib>
<forced_lib>msvcrt</forced_lib>
<forced_lib>multiprocessing</forced_lib>
<forced_lib>nt</forced_lib>
<forced_lib>numpy</forced_lib>
<forced_lib>operator</forced_lib>
<forced_lib>os</forced_lib>
<forced_lib>os.path</forced_lib>
<forced_lib>parser</forced_lib>
<forced_lib>pytest</forced_lib>
<forced_lib>scipy</forced_lib>
<forced_lib>signal</forced_lib>
<forced_lib>socket</forced_lib>
<forced_lib>strop</forced_lib>
<forced_lib>sys</forced_lib>
<forced_lib>thread</forced_lib>
<forced_lib>time</forced_lib>
<forced_lib>winreg</forced_lib>
<forced_lib>wx</forced_lib>
<forced_lib>wxPython</forced_lib>
<forced_lib>xxsubtype</forced_lib>
<forced_lib>zipimport</forced_lib>
<forced_lib>zlib</forced_lib>
</xml>

	at org.python.pydev.core.log.Log.logInfo(Log.java:66)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker.autoConfigSingleApply(AutoConfigMaker.java:177)
	at org.python.pydev.ui.PyProjectPythonDetails$ProjectInterpreterAndGrammarConfig$2.widgetSelected(PyProjectPythonDetails.java:273)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1120)
	at org.eclipse.swt.widgets.Link.WM_LBUTTONUP(Link.java:1035)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4828)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5115)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2552)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3814)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.actions.NewProjectAction.run(NewProjectAction.java:115)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.jface.action.ActionContributionItem$$Lambda$40/1267115606.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

!ENTRY org.python.pydev.shared_core 1 1 2016-08-16 10:39:07.760
!MESSAGE Restoring info for: C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe
!STACK 0
java.lang.RuntimeException: Restoring info for: C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getInterpretersFromPersistedString(AbstractInterpreterManager.java:529)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.internalRecreateCacheGetInterpreterInfos(AbstractInterpreterManager.java:345)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:655)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker$1.run(AutoConfigMaker.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Expecting: C:\Users\nikhil_mohandas\eclipse\neon\Python\.metadata\.plugins\org.python.pydev\v1_rmfil5f54metxgtaox8nk4ci\modulesKeys to exist (and be a file).
	at org.python.pydev.editor.codecompletion.revisited.ModulesManager.loadFromFile(ModulesManager.java:293)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.load(SystemModulesManager.java:386)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getInterpretersFromPersistedString(AbstractInterpreterManager.java:527)
	... 4 more

!ENTRY org.python.pydev.shared_core 1 1 2016-08-16 10:39:14.236
!MESSAGE Finished restoring information for: C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe at: C:\Users\nikhil_mohandas\eclipse\neon\Python\.metadata\.plugins\org.python.pydev\v1_rmfil5f54metxgtaox8nk4ci
!STACK 0
java.lang.RuntimeException: Finished restoring information for: C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe at: C:\Users\nikhil_mohandas\eclipse\neon\Python\.metadata\.plugins\org.python.pydev\v1_rmfil5f54metxgtaox8nk4ci
	at org.python.pydev.core.log.Log.logInfo(Log.java:66)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getInterpretersFromPersistedString(AbstractInterpreterManager.java:574)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.internalRecreateCacheGetInterpreterInfos(AbstractInterpreterManager.java:345)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:655)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker$1.run(AutoConfigMaker.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-16 10:39:15.602
!MESSAGE Info: Rebuilding internal caches: C:\Users\nikhil_mohandas\eclipse\neon\Python\.metadata\.plugins\com.python.pydev.analysis\python_v1_rmfil5f54metxgtaox8nk4ci\python.pydevsysteminfo (Expected error to be provided and got no error!)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-16 10:39:21.956
!MESSAGE Info: Rebuilding internal caches: C:\Users\nikhil_mohandas\eclipse\neon\Python\.metadata\.plugins\org.eclipse.core.resources\.projects\48MonthsDBOrderRelated\com.python.pydev.analysis\AdditionalProjectInterpreterInfo.pydevinfo (Expected error to be provided and got no error!)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-16 10:39:37.045
!MESSAGE Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=hard_break, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=nospace, ctx=Attrib], ctx=Load]], value=null] (module: formatter.py).
!STACK 0
java.lang.RuntimeException: Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=hard_break, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=nospace, ctx=Attrib], ctx=Load]], value=null] (module: formatter.py).
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.endScopesInStack(FastDefinitionsParser.java:589)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.handleNewLine(FastDefinitionsParser.java:380)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.extractBody(FastDefinitionsParser.java:249)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.parse(FastDefinitionsParser.java:676)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:314)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:264)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:36)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:740)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:657)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker$1.run(AutoConfigMaker.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-16 10:39:37.046
!MESSAGE Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=nospace, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=para_end, ctx=Attrib], ctx=Load]], value=null] (module: formatter.py).
!STACK 0
java.lang.RuntimeException: Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=nospace, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=para_end, ctx=Attrib], ctx=Load]], value=null] (module: formatter.py).
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.endScopesInStack(FastDefinitionsParser.java:589)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.handleNewLine(FastDefinitionsParser.java:380)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.extractBody(FastDefinitionsParser.java:249)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.parse(FastDefinitionsParser.java:676)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:314)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:264)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:36)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:740)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:657)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker$1.run(AutoConfigMaker.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-16 10:39:37.047
!MESSAGE Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=hard_break, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=para_end, ctx=Attrib], ctx=Load]], value=null] (module: formatter.py).
!STACK 0
java.lang.RuntimeException: Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=hard_break, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=para_end, ctx=Attrib], ctx=Load]], value=null] (module: formatter.py).
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.endScopesInStack(FastDefinitionsParser.java:589)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.handleNewLine(FastDefinitionsParser.java:380)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.extractBody(FastDefinitionsParser.java:249)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.parse(FastDefinitionsParser.java:676)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:314)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:264)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:36)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:740)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:657)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker$1.run(AutoConfigMaker.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-16 10:39:40.334
!MESSAGE Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=_weakref, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=_callback, ctx=Attrib], ctx=Load]], value=null] (module: util.py).
!STACK 0
java.lang.RuntimeException: Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=_weakref, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=_callback, ctx=Attrib], ctx=Load]], value=null] (module: util.py).
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.endScopesInStack(FastDefinitionsParser.java:589)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.handleNewLine(FastDefinitionsParser.java:380)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.extractBody(FastDefinitionsParser.java:249)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.parse(FastDefinitionsParser.java:676)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:314)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:264)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:36)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:740)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:657)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker$1.run(AutoConfigMaker.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-16 10:39:57.897
!MESSAGE Did not expect to find item below node: Assign[targets=[Name[id=argsParseTuple, ctx=Store, reserved=false], Name[id=argsCOM, ctx=Store, reserved=false], Name[id=formatChars, ctx=Store, reserved=false]], value=null] (module: makegw.py).
!STACK 0
java.lang.RuntimeException: Did not expect to find item below node: Assign[targets=[Name[id=argsParseTuple, ctx=Store, reserved=false], Name[id=argsCOM, ctx=Store, reserved=false], Name[id=formatChars, ctx=Store, reserved=false]], value=null] (module: makegw.py).
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.endScopesInStack(FastDefinitionsParser.java:589)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.handleNewLine(FastDefinitionsParser.java:380)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.extractBody(FastDefinitionsParser.java:249)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.parse(FastDefinitionsParser.java:676)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:314)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:264)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:36)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:740)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:657)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker$1.run(AutoConfigMaker.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-16 10:40:03.334
!MESSAGE Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=hard_break, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=nospace, ctx=Attrib], ctx=Load]], value=null] (module: formatter.py).
!STACK 0
java.lang.RuntimeException: Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=hard_break, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=nospace, ctx=Attrib], ctx=Load]], value=null] (module: formatter.py).
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.endScopesInStack(FastDefinitionsParser.java:589)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.handleNewLine(FastDefinitionsParser.java:380)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.extractBody(FastDefinitionsParser.java:249)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.parse(FastDefinitionsParser.java:676)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:314)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:264)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:36)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:740)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:657)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker$1.run(AutoConfigMaker.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-16 10:40:03.336
!MESSAGE Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=nospace, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=para_end, ctx=Attrib], ctx=Load]], value=null] (module: formatter.py).
!STACK 0
java.lang.RuntimeException: Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=nospace, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=para_end, ctx=Attrib], ctx=Load]], value=null] (module: formatter.py).
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.endScopesInStack(FastDefinitionsParser.java:589)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.handleNewLine(FastDefinitionsParser.java:380)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.extractBody(FastDefinitionsParser.java:249)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.parse(FastDefinitionsParser.java:676)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:314)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:264)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:36)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:740)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:657)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker$1.run(AutoConfigMaker.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-16 10:40:03.337
!MESSAGE Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=hard_break, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=para_end, ctx=Attrib], ctx=Load]], value=null] (module: formatter.py).
!STACK 0
java.lang.RuntimeException: Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=hard_break, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=para_end, ctx=Attrib], ctx=Load]], value=null] (module: formatter.py).
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.endScopesInStack(FastDefinitionsParser.java:589)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.handleNewLine(FastDefinitionsParser.java:380)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.extractBody(FastDefinitionsParser.java:249)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.parse(FastDefinitionsParser.java:676)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:314)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:264)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:36)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:740)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:657)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker$1.run(AutoConfigMaker.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-16 10:40:03.532
!MESSAGE Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=_weakref, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=_callback, ctx=Attrib], ctx=Load]], value=null] (module: util.py).
!STACK 0
java.lang.RuntimeException: Did not expect to find item below node: Assign[targets=[Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=_weakref, ctx=Attrib], ctx=Load], Attribute[value=Name[id=self, ctx=Load, reserved=false], attr=NameTok[id=_callback, ctx=Attrib], ctx=Load]], value=null] (module: util.py).
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.endScopesInStack(FastDefinitionsParser.java:589)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.handleNewLine(FastDefinitionsParser.java:380)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.extractBody(FastDefinitionsParser.java:249)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.parse(FastDefinitionsParser.java:676)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:314)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:264)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:36)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:740)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:657)
	at org.python.pydev.ui.pythonpathconf.AutoConfigMaker$1.run(AutoConfigMaker.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-16 10:40:06.533
!MESSAGE ERROR reading shell.
!STACK 0
java.lang.RuntimeException: The shell is still not connected, so, it is an invalid state to try to write to it.
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.write(AbstractShell.java:527)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.writeAndGetResults(AbstractShell.java:691)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.internalChangePythonPath(AbstractShell.java:737)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getImportCompletions(AbstractShell.java:755)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createTokensFromServer(CompiledModule.java:363)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.<init>(CompiledModule.java:168)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getBuiltinModule(SystemModulesManager.java:321)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getBuiltinModule(SystemModulesManager.java:1)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getBuiltinMod(AbstractInterpreterManager.java:146)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getBuiltinCompletions(AbstractInterpreterManager.java:118)
	at org.python.pydev.plugin.nature.PythonNature.getBuiltinCompletions(PythonNature.java:1052)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getBuiltinComps(AbstractASTManager.java:1635)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getBuiltinCompletions(AbstractASTManager.java:1621)
	at com.python.pydev.analysis.scopeanalysis.AbstractScopeAnalyzerVisitor.<init>(AbstractScopeAnalyzerVisitor.java:150)
	at com.python.pydev.analysis.visitors.OccurrencesVisitor.<init>(OccurrencesVisitor.java:90)
	at com.python.pydev.analysis.OccurrencesAnalyzer.analyzeDocument(OccurrencesAnalyzer.java:50)
	at com.python.pydev.analysis.builder.AnalysisBuilderRunnable.doAnalysis(AnalysisBuilderRunnable.java:251)
	at com.python.pydev.analysis.builder.AbstractAnalysisBuilderRunnable.run(AbstractAnalysisBuilderRunnable.java:162)
	at org.python.pydev.core.concurrency.RunnableAsJobsPoolThread$1.run(RunnableAsJobsPoolThread.java:140)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.core.jobs 4 2 2016-08-16 11:04:25.992
!MESSAGE An internal error occurred during: "Reading saved version of file for quick diff".
!STACK 0
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.lang.AbstractStringBuilder.expandCapacity(Unknown Source)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuffer.append(Unknown Source)
	at org.eclipse.ui.internal.editors.quickdiff.LastSaveReferenceProvider.setDocumentContent(LastSaveReferenceProvider.java:381)
	at org.eclipse.ui.internal.editors.quickdiff.LastSaveReferenceProvider.readDocument(LastSaveReferenceProvider.java:242)
	at org.eclipse.ui.internal.editors.quickdiff.LastSaveReferenceProvider.access$0(LastSaveReferenceProvider.java:193)
	at org.eclipse.ui.internal.editors.quickdiff.LastSaveReferenceProvider$ReadJob.run(LastSaveReferenceProvider.java:115)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.ltk.ui.refactoring 4 10000 2016-08-16 11:29:50.524
!MESSAGE Internal Error
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:795)
	at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:163)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
	at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Contains: Could not delete 'C:\Users\nikhil_mohandas\eclipse\neon\Python\48MonthsDBOrderRelated\src\RecordInserted.log'.
org.eclipse.core.runtime.CoreException: Problems encountered while deleting files.
	at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:138)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFile(ResourceTree.java:310)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteFile(ResourceTree.java:796)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1828)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:782)
	at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:163)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
	at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Contains: Could not delete: C:\Users\nikhil_mohandas\eclipse\neon\Python\48MonthsDBOrderRelated\src\RecordInserted.log.
java.nio.file.FileSystemException: C:\Users\nikhil_mohandas\eclipse\neon\Python\48MonthsDBOrderRelated\src\RecordInserted.log: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
	at java.nio.file.Files.deleteIfExists(Unknown Source)
	at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:218)
	at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:136)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFile(ResourceTree.java:310)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteFile(ResourceTree.java:796)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1828)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:782)
	at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:163)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
	at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
!SUBENTRY 1 org.eclipse.core.resources 4 273 2016-08-16 11:29:50.526
!MESSAGE Problems encountered while deleting resources.
!SUBENTRY 2 org.eclipse.core.resources 4 273 2016-08-16 11:29:50.526
!MESSAGE Could not delete 'C:\Users\nikhil_mohandas\eclipse\neon\Python\48MonthsDBOrderRelated\src\RecordInserted.log'.
!STACK 1
org.eclipse.core.runtime.CoreException: Problems encountered while deleting files.
	at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:138)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFile(ResourceTree.java:310)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteFile(ResourceTree.java:796)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1828)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:782)
	at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:163)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
	at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Contains: Could not delete: C:\Users\nikhil_mohandas\eclipse\neon\Python\48MonthsDBOrderRelated\src\RecordInserted.log.
java.nio.file.FileSystemException: C:\Users\nikhil_mohandas\eclipse\neon\Python\48MonthsDBOrderRelated\src\RecordInserted.log: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
	at java.nio.file.Files.deleteIfExists(Unknown Source)
	at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:218)
	at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:136)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFile(ResourceTree.java:310)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteFile(ResourceTree.java:796)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1828)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:782)
	at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:163)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
	at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
!SUBENTRY 3 org.eclipse.core.filesystem 4 273 2016-08-16 11:29:50.526
!MESSAGE Problems encountered while deleting files.
!SUBENTRY 4 org.eclipse.core.filesystem 4 273 2016-08-16 11:29:50.526
!MESSAGE Could not delete: C:\Users\nikhil_mohandas\eclipse\neon\Python\48MonthsDBOrderRelated\src\RecordInserted.log.
!STACK 0
java.nio.file.FileSystemException: C:\Users\nikhil_mohandas\eclipse\neon\Python\48MonthsDBOrderRelated\src\RecordInserted.log: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
	at java.nio.file.Files.deleteIfExists(Unknown Source)
	at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:218)
	at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:136)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFile(ResourceTree.java:310)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteFile(ResourceTree.java:796)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1828)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:782)
	at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:163)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
	at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

!ENTRY org.eclipse.core.resources 4 273 2016-08-16 11:29:50.528
!MESSAGE Problems encountered while deleting resources.
!SUBENTRY 1 org.eclipse.core.resources 4 273 2016-08-16 11:29:50.528
!MESSAGE Could not delete 'C:\Users\nikhil_mohandas\eclipse\neon\Python\48MonthsDBOrderRelated\src\RecordInserted.log'.
!STACK 1
org.eclipse.core.runtime.CoreException: Problems encountered while deleting files.
	at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:138)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFile(ResourceTree.java:310)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteFile(ResourceTree.java:796)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1828)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:782)
	at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:163)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
	at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Contains: Could not delete: C:\Users\nikhil_mohandas\eclipse\neon\Python\48MonthsDBOrderRelated\src\RecordInserted.log.
java.nio.file.FileSystemException: C:\Users\nikhil_mohandas\eclipse\neon\Python\48MonthsDBOrderRelated\src\RecordInserted.log: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
	at java.nio.file.Files.deleteIfExists(Unknown Source)
	at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:218)
	at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:136)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFile(ResourceTree.java:310)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteFile(ResourceTree.java:796)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1828)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:782)
	at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:163)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
	at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
!SUBENTRY 2 org.eclipse.core.filesystem 4 273 2016-08-16 11:29:50.528
!MESSAGE Problems encountered while deleting files.
!SUBENTRY 3 org.eclipse.core.filesystem 4 273 2016-08-16 11:29:50.528
!MESSAGE Could not delete: C:\Users\nikhil_mohandas\eclipse\neon\Python\48MonthsDBOrderRelated\src\RecordInserted.log.
!STACK 0
java.nio.file.FileSystemException: C:\Users\nikhil_mohandas\eclipse\neon\Python\48MonthsDBOrderRelated\src\RecordInserted.log: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
	at java.nio.file.Files.deleteIfExists(Unknown Source)
	at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:218)
	at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:136)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFile(ResourceTree.java:310)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteFile(ResourceTree.java:796)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1828)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:782)
	at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:163)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
	at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-16 11:44:26.857
!MESSAGE Did not expect to find item below node: Assign[targets=[Name[id=fh, ctx=Store, reserved=false]], value=null] (module: NewRecordInserted).
!STACK 0
java.lang.RuntimeException: Did not expect to find item below node: Assign[targets=[Name[id=fh, ctx=Store, reserved=false]], value=null] (module: NewRecordInserted).
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.endScopesInStack(FastDefinitionsParser.java:589)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.handleNewLine(FastDefinitionsParser.java:380)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.extractBody(FastDefinitionsParser.java:249)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.parse(FastDefinitionsParser.java:676)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.parse(FastDefinitionsParser.java:670)
	at org.python.pydev.parser.fastparser.FastDefinitionsParser.parse(FastDefinitionsParser.java:661)
	at com.python.pydev.analysis.builder.AnalysisBuilderVisitor$1.call(AnalysisBuilderVisitor.java:114)
	at com.python.pydev.analysis.builder.AnalysisBuilderVisitor$1.call(AnalysisBuilderVisitor.java:1)
	at com.python.pydev.analysis.builder.AnalysisBuilderRunnable.<init>(AnalysisBuilderRunnable.java:152)
	at com.python.pydev.analysis.builder.AnalysisBuilderRunnableFactory.createRunnable(AnalysisBuilderRunnableFactory.java:222)
	at com.python.pydev.analysis.builder.AnalysisBuilderVisitor.doVisitChangedResource(AnalysisBuilderVisitor.java:179)
	at com.python.pydev.analysis.builder.AnalysisBuilderVisitor.visitChangedResource(AnalysisBuilderVisitor.java:128)
	at com.python.pydev.analysis.builder.AnalysisBuilderVisitor.visitChangedResource(AnalysisBuilderVisitor.java:45)
	at org.python.pydev.builder.PydevGrouperVisitor.visitWith(PydevGrouperVisitor.java:115)
	at org.python.pydev.builder.PydevGrouperVisitor.visitChangedResource(PydevGrouperVisitor.java:166)
	at org.python.pydev.builder.PydevGrouperVisitor.finishDelayedVisits(PydevGrouperVisitor.java:190)
	at org.python.pydev.builder.PyDevBuilder.build(PyDevBuilder.java:135)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.jface 2 0 2016-08-16 14:38:01.629
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-08-16 14:38:01.629
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@4b88d9cf,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@11adfdff,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3dfdd648,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-17 10:18:09.691
!MESSAGE ERROR reading shell.
ProcessInfo:

 - Executed: C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\python.exe -u C:\Users\nikhil_mohandas\.p2\pool\plugins\org.python.pydev_5.1.2.201606231256\pysrc\pycompletionserver.py 58595

 - Environment:
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\nikhil_mohandas\AppData\Roaming
CATALINA_HOME=D:\tools\apache-tomcat-6.0.18
CLASSPATH=.
COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMMONPROGRAMW6432=C:\Program Files\Common Files
COMPUTERNAME=TH1250
COMSPEC=C:\Windows\system32\cmd.exe
DEFLOGDIR=C:\ProgramData\McAfee\DesktopProtection
FP_NO_HOST_CHECK=NO
HOMEDRIVE=C:
HOMEPATH=\Users\nikhil_mohandas
JAVA_HOME8=C:\Program Files\Java\jdk1.6.0_45
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_51
JRE_HOME8=C:\Program Files\Java\jdk1.6.0_45\jre
JRE_HOME=C:\Program Files\Java\jdk1.8.0_51\jre
LOCALAPPDATA=C:\Users\nikhil_mohandas\AppData\Local
LOGONSERVER=\\EAGLE
MAVEN_HOME=D:\tools\apache-maven-3.2.5
MVN_HOME=D:\tools\apache-maven-3.2.5
NUMBER_OF_PROCESSORS=4
OS=Windows_NT
PATH8=D:\tools\apache-tomcat-6.0.18\bin;C:\Program Files\Java\jdk1.6.0_45\bin
PATH=C:\oraclexe\app\oracle\product\11.2.0\server\bin;;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\PROGRA~2\GNU\WINCVS~1.3\CVSNT;C:\Program Files (x86)\Skype\Phone\;D:\tools\apache-maven-3.2.5\bin;C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\;C:\Program Files\Java\jdk1.8.0_51\bin;D:\tools\Oracleclient\instantclient_10_2;C:\Python33;C:\wamp64\www\Zend
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3c03
PROGRAMDATA=C:\ProgramData
PROGRAMFILES(X86)=C:\Program Files (x86)
PROGRAMFILES=C:\Program Files
PROGRAMW6432=C:\Program Files
PROMPT=$P$G
PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
PYTHONPATH=C:\Users\nikhil_mohandas\.p2\pool\plugins\org.python.pydev_5.1.2.201606231256\pysrc\pydev_sitecustomize;C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools-24.0.2-py3.5.egg;C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\email-6.0.0a1-py3.5.egg;C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\DLLs;C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib;C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35;C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages;C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\win32;C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\win32\lib;C:\Users\nikhil_mohandas\AppData\Local\Programs\Python\Python35\lib\site-packages\Pythonwin
SESSIONNAME=Console
SYSTEMDRIVE=C:
SYSTEMROOT=C:\Windows
TEMP=C:\Users\NIKHIL~1\AppData\Local\Temp
TMP=C:\Users\NIKHIL~1\AppData\Local\Temp
TOMCAT_HOME=D:\tools\apache-tomcat-6.0.18
USERDNSDOMAIN=THBS.INDIA.COM
USERDOMAIN=THBS
USERDOMAIN_ROAMINGPROFILE=THBS
USERNAME=nikhil_mohandas
USERPROFILE=C:\Users\nikhil_mohandas
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
VSEDEFLOGDIR=C:\ProgramData\McAfee\DesktopProtection
WINDIR=C:\Windows

 - Working Dir:
C:\Users\nikhil_mohandas\eclipse\java-neon\eclipse\..\..\..\.p2\pool\plugins\org.python.pydev_5.1.2.201606231256\pysrc

 - OS:
Windows 8.1

 - Std output:


 - Err output:

!STACK 0
java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.poll(Unknown Source)
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(Unknown Source)
	at sun.nio.ch.ChannelInputStream.read(Unknown Source)
	at java.io.InputStream.read(Unknown Source)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.read(AbstractShell.java:454)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.read(AbstractShell.java:506)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.writeAndGetResults(AbstractShell.java:692)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getLineCol(AbstractShell.java:776)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:597)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:1)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1098)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:971)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:953)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:666)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getDocstringHover(PyDocstringTextHover.java:100)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getHoverInfo(PyDocstringTextHover.java:58)
	at org.python.pydev.editor.hover.PydevCombiningHover.getHoverInfo(PydevCombiningHover.java:152)
	at org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverInfo(PyEditorTextHoverProxy.java:59)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:167)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-17 10:18:17.087
!MESSAGE The python client still hasn't connected back to the eclipse java vm (will retry...)
!STACK 0
java.lang.RuntimeException: The python client still hasn't connected back to the eclipse java vm (will retry...)
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:334)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.restartShell(AbstractShell.java:654)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.writeAndGetResults(AbstractShell.java:703)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getLineCol(AbstractShell.java:776)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:597)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.findDefinition(CompiledModule.java:1)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1098)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:971)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:953)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:666)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:182)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getDocstringHover(PyDocstringTextHover.java:100)
	at org.python.pydev.editor.hover.PyDocstringTextHover.getHoverInfo(PyDocstringTextHover.java:58)
	at org.python.pydev.editor.hover.PydevCombiningHover.getHoverInfo(PydevCombiningHover.java:152)
	at org.python.pydev.editor.hover.PyEditorTextHoverProxy.getHoverInfo(PyEditorTextHoverProxy.java:59)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:167)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-17 10:31:05.929
!MESSAGE No message gotten (null message).
!STACK 0
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1051)
	at org.eclipse.jface.text.TreeLineTracker.getLineInformation(TreeLineTracker.java:1160)
	at org.eclipse.jface.text.AbstractLineTracker.getLineInformation(AbstractLineTracker.java:133)
	at org.eclipse.jface.text.AbstractDocument.getLineInformation(AbstractDocument.java:877)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineInformation(SynchronizableDocument.java:287)
	at org.python.pydev.shared_core.string.TextSelectionUtils.getStartLine(TextSelectionUtils.java:164)
	at org.python.pydev.editor.refactoring.RefactoringRequest.getBeginCol(RefactoringRequest.java:201)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:78)
	at com.python.pydev.refactoring.refactorer.RefactorerFindDefinition.findDefinition(RefactorerFindDefinition.java:63)
	at com.python.pydev.refactoring.refactorer.Refactorer.findDefinition(Refactorer.java:119)
	at com.python.pydev.refactoring.wizards.rename.PyReferenceSearcher.prepareSearch(PyReferenceSearcher.java:110)
	at com.python.pydev.refactoring.markoccurrences.MarkOccurrencesJob.createRequest(MarkOccurrencesJob.java:147)
	at org.python.pydev.shared_ui.mark_occurrences.BaseMarkOccurrencesJob.run(BaseMarkOccurrencesJob.java:168)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.python.pydev.shared_core 4 4 2016-08-17 10:31:49.320
!MESSAGE No message gotten (null message).
!STACK 0
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1051)
	at org.eclipse.jface.text.TreeLineTracker.getLineInformation(TreeLineTracker.java:1160)
	at org.eclipse.jface.text.AbstractLineTracker.getLineInformation(AbstractLineTracker.java:133)
	at org.eclipse.jface.text.AbstractDocument.getLineInformation(AbstractDocument.java:877)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineInformation(SynchronizableDocument.java:287)
	at org.python.pydev.shared_core.string.TextSelectionUtils.getStartLine(TextSelectionUtils.java:164)
	at org.python.pydev.editor.refactoring.RefactoringRequest.getBeginCol(RefactoringRequest.java:201)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:78)
	at com.python.pydev.refactoring.refactorer.RefactorerFindDefinition.findDefinition(RefactorerFindDefinition.java:63)
	at com.python.pydev.refactoring.refactorer.Refactorer.findDefinition(Refactorer.java:119)
	at com.python.pydev.refactoring.wizards.rename.PyReferenceSearcher.prepareSearch(PyReferenceSearcher.java:110)
	at com.python.pydev.refactoring.markoccurrences.MarkOccurrencesJob.createRequest(MarkOccurrencesJob.java:147)
	at org.python.pydev.shared_ui.mark_occurrences.BaseMarkOccurrencesJob.run(BaseMarkOccurrencesJob.java:168)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.equinox.p2.engine 4 4 2016-08-17 11:12:50.979
!MESSAGE An error occurred while collecting items to be installed
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2016-08-17 11:12:50.979
!MESSAGE session context was:(profile=C__Users_nikhil_mohandas_eclipse_java-neon_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.core,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.doc,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.mylyn.ui,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.ui,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.archive,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.core.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.egit,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.gitflow,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.egit.gitflow.feature,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.gitflow.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.gitflow.ui,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.gitflow.ui.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.egit.mylyn,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.mylyn.ui.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.egit.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.ui.smartimport,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.ui.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.jgit,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.http.apache,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.jgit.http.apache,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.lfs,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.jgit.lfs,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.lfs.server,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.pgm,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.jgit.pgm,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.pgm.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.jgit.pgm.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.jgit.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:12:50.979
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.ui,4.4.1.201607150455-r

!ENTRY org.eclipse.equinox.p2.engine 4 4 2016-08-17 11:39:25.841
!MESSAGE An error occurred while collecting items to be installed
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2016-08-17 11:39:25.841
!MESSAGE session context was:(profile=C__Users_nikhil_mohandas_eclipse_java-neon_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.core,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.doc,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.mylyn.ui,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.ui,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.archive,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.core.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.egit,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.gitflow,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.egit.gitflow.feature,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.gitflow.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.gitflow.ui,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.gitflow.ui.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.egit.mylyn,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.mylyn.ui.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.egit.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.ui.smartimport,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.egit.ui.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.jgit,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.http.apache,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.jgit.http.apache,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.lfs,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.jgit.lfs,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.lfs.server,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.pgm,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.jgit.pgm,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.pgm.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.jgit.pgm.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.jgit.source,4.4.1.201607150455-r
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2016-08-17 11:39:25.841
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.jgit.ui,4.4.1.201607150455-r
